### ISSUE TITLE
Unable to build project on OS X

### ISSUE THREAD

**Issue by ccday** [chandlerD6/PhotoLab-Dynamic#1]
Hello,

I get the error ```make: *** No rule to make target `Constants.h', needed by `FileIO.o'.  Stop.``` when I try to build your project. Please fix this, this software is important to my business.

Thanks.

**Comment by chandlerD6** [comment]
Sorry for the inconvenience. I quickly fixed the issue as soon as I could. Constants.h has been included to the repository. For any further assistance please email me at Funnybunny17@aol.com.

**Comment by ccday** [comment]
Thank you, I will be sending check soon.
